
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 31 22:17:05 CEST 2018
//----------------------------------------------------

package svgTester.twitterHandling.BVG;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 5;
  public static final int VERKEHRT = 11;
  public static final int DATE = 2;
  public static final int TIME = 3;
  public static final int ZURZEIT = 7;
  public static final int HASH = 6;
  public static final int EOF = 0;
  public static final int NICHTZWISCHEN = 10;
  public static final int ZERO = 14;
  public static final int URL = 13;
  public static final int error = 1;
  public static final int AT = 15;
  public static final int NURZWISCHEN = 9;
  public static final int UHR = 8;
  public static final int LINE = 4;
  public static final int WORD = 12;
}

