
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jan 10 16:59:08 CET 2018
//----------------------------------------------------

package svgTester.svg;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ANF = 15;
  public static final int SEMICOLON = 9;
  public static final int IDENT = 6;
  public static final int INT = 3;
  public static final int ENDTAG = 14;
  public static final int CHAR = 5;
  public static final int VALUE = 17;
  public static final int KOORDS = 18;
  public static final int COLOR = 10;
  public static final int URL = 16;
  public static final int COLON = 8;
  public static final int HEADERTAG = 11;
  public static final int ROT = 20;
  public static final int COMMA = 19;
  public static final int EOF = 0;
  public static final int CLOSETAG = 13;
  public static final int error = 1;
  public static final int PRECENT = 21;
  public static final int EQ = 7;
  public static final int ZERO = 2;
  public static final int OPENTAG = 12;
  public static final int REAL = 4;
}

